drop table if exists market CASCADE;
create table market
(
    id INTEGER generated by default as identity,
    name varchar (255),
    owner varchar (255),
    description varchar (255),
    level INTEGER (3),
    address varchar (255),
    phone varchar (255),
    holidays varchar (255),

    primary key (id)
);

drop table if exists time CASCADE;

create table times
(
    id INTEGER generated by default as identity,
    day varchar (255),
    open varchar (255),
    close varchar (255),
    marketId INTEGER,
    primary key (id),
    foreign key (marketId) references market(id)
);